server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Freerauner12
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
    hibetnate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true


indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
      order: 1
#
#    - url: https://ipfran.ru/
#      name: ИПФ
#      order: 2
#
#    - url: https://nikoartgallery.com/
#      name: Галерея Нико
#      order: 3

